### ISSUE TITLE
Combining fileNode and text/markdown mappings

### ISSUE THREAD

**Issue by akiarostami** [jbolda/gatsby-source-airtable#301]
This is previously reported bug (#41) which seems to be unresolved. I couldn't re-open the old one, so I filed a new issue. I hope that's fine.

When I have either fileNode or text/markdown in a single table's mapping, everything seems to be fine. But when I have both for one table I see the following error:

```
AirtableField.raw:
 - type: array
   value: [ ..., { id: 'atte2xZRBwvF4U3UI', url: 'https://dl.airtable.com/.attachments/746a07721477d9cd1e54d05a9ab60856/0d3929eb/picture.jpg', filename:
'picture.jpg', size: 138519, type: 'image/jpeg', thumbnails: [Object] }, ... ]
 - type: string
   value: 'Welcome to out blog.\n'
```
